### PR TITLE
Finalized version of clang-format

### PR DESCRIPTION
**Pull request by j-stephan**
This is the (continuously updated) `.clang-format` file which reflects the votes made in #39. **This topic is not intended for discussion or voting; use #39 instead.** Once the voting process is over and all changes have been introduced to this PR it will be merged.

### CODE REVIEW

**Comment by j-stephan** [comment]
This is now ready to merge. @psychocoderHPC @sbastrakov

**Review by sbastrakov — APPROVED** [review]

**Comment by sbastrakov** [comment]
@psychocoderHPC I can't merge in this repo.

**Comment by psychocoderHPC** [comment]
merged

**Comment by psychocoderHPC** [comment]
Fighting with the usage of the clang format https://github.com/alpaka-group/alpaka/pull/1204

Which clang version is required

**Pull request merged**
