### PR TITLE
[clang-tidy] Vote: Add various HPC checks

### PR DESCRIPTION
**Pull request by j-stephan**
Voting will close on 23 September EOD (HZDR time).

Titled "Various HPC" because this PR deals with multithreading, precision, random numbers, OpenMP and MPI.

* Don't use `SIGTERM` to kill a POSIX thread - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/bugprone-bad-signal-to-kill-thread.html)
* Find static variables that are dynamically initialized in header files - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/bugprone-dynamic-static-initializers.html)
* Find precision loss in folds - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/bugprone-fold-init-type.html)
* Find programming patterns that lead to incorrect rounding - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/bugprone-incorrect-roundings.html)
* Find float-by-integer divisions that lead to unexpected precision losses - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/bugprone-integer-division.html)
* Find pointers attributed with `[[clang::noescape]]` that in fact escape - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/bugprone-no-escape.html). The attribute is described [here](https://clang.llvm.org/docs/AttributeReference.html#noescape).
* Find wake-up functions that can spuriously wake up - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/bugprone-spuriously-wake-up-functions.html)
* Do not use `std::rand` - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/cert-msc50-cpp.html)
* Do not use default arguments, constant expressions or user-configurable types as seeds for RNGs. - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/cert-msc51-cpp.html)
* Use sufficiently dereferenced pointers when interacting with MPI - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/mpi-buffer-deref.html)
* Find type mismatches when interacting with MPI - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/mpi-type-mismatch.html)
* Find exceptions that (illegally) escape OpenMP blocks - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/openmp-exception-escape.html)
* Find OpenMP blocks that should be `default(none)` but aren't - [Link](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/openmp-use-default-none.html)

### Vote template

```markdown
Check | Yes | No | Comment
------|-----|----|--------
Don't kill pthreads with `SIGTERM` | X | X | X
Find dynamically initialized static vars | X | X | X
Precision loss in folds | X | X | X
Incorrect rounding patterns | X | X | X
Lossy float-by-int divisions | X | X | X
`[[clang::noescape]]` | X | X | X
Wake-up functions | X | X | X
Don't use `std::rand` | X | X | X
Bad seeds for RNG | X | X | X
Dereferencing pointers for MPI | X | X | X
Type mismatches for MPI | X | X | X
OpenMP exception safety | X | X | X
`default(none)` OpenMP blocks | X | X | X
```

### Vote

Check | Yes | No | Comment
------|-----|----|--------
Don't kill pthreads with `SIGTERM` | 1 | 0 | -
Find dynamically initialized static vars | 1 | 0 | -
Precision loss in folds | 1 | 0 | -
Incorrect rounding patterns | 1 | 0 | -
Lossy float-by-int divisions | 1 | 0 | -
`[[clang::noescape]]` | 1 | 0 | AFAIK we don't use the attribute but the inclusion doesn't hurt.
Wake-up functions | 1 | 0 | -
Don't use `std::rand` | 0 | 1 | Soft no. IMO we're not working in a security environment but maybe I need to be convinced.
Bad seeds for RNG | 0 | 1 | Same as above.
Dereferencing pointers for MPI | 1 | 0 | -
Type mismatches for MPI | 1 | 0 | -
OpenMP exception safety | 1 | 0 | -
`default(none)` OpenMP blocks | 1 | 0 | -

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
Check | Yes | No | Comment
------|-----|----|--------
Don't kill pthreads with `SIGTERM` | 3 | 0 | -
Find dynamically initialized static vars | 3 | 0 | -
Precision loss in folds | 3 | 0 | -
Incorrect rounding patterns | 3 | 0 | -
Lossy float-by-int divisions | 3 | 0 | -
`[[clang::noescape]]` | 3 | 0 | -
Wake-up functions | 3 | 0 | -
Don't use `std::rand` | 1 | 1 | I have not enough experience with random number. `<random>` worked for me all the time. 
Bad seeds for RNG | 0 | 3 | -
Dereferencing pointers for MPI | 3 | 0 | -
Type mismatches for MPI | 3 | 0 | -
OpenMP exception safety | 3 | 0 | -
`default(none)` OpenMP blocks | 1 | 1 | -

**Comment by j-stephan** [comment]
@psychocoderHPC Please tie-break on the OpenMP issue. I change my vote for `std::rand` as follows:

Check | Yes | No | Comment
------|-----|----|--------
Don't kill pthreads with `SIGTERM` | 3 | 0 | -
Find dynamically initialized static vars | 3 | 0 | -
Precision loss in folds | 3 | 0 | -
Incorrect rounding patterns | 3 | 0 | -
Lossy float-by-int divisions | 3 | 0 | -
`[[clang::noescape]]` | 3 | 0 | -
Wake-up functions | 3 | 0 | -
Don't use `std::rand` | 2 | 0 | Updated
Bad seeds for RNG | 0 | 3 | -
Dereferencing pointers for MPI | 3 | 0 | -
Type mismatches for MPI | 3 | 0 | -
OpenMP exception safety | 3 | 0 | -
`default(none)` OpenMP blocks | 1 | 1 | -

**Comment by psychocoderHPC** [comment]
I can not tie-break because I do not understand the rule for `default(none) OpenMP blocks` fully.
What effect does this option have on alpaka, PIConGPU?

**Comment by j-stephan** [comment]
I can only speak for alpaka.

* Omp2Blocks: Warns on one instance
* Omp2Threads: Warns on one instance
* Omp5: Warns on one instance

It will basically always print a warning in the following case:

```c++
#pragma omp parallel
```

And wants it transformed to this:

```c++
#pragma omp parallel default(none)
```

The practical effect of this: Without `default(none)`, all variables are shared. With `default(none)` you will have to explicitly specify which variables are private and which are shared:

```c++
#pragma omp parallel default(none) private(a, b) shared(x, y)
```

This ties in nicely with alpaka's philosophy of making everything explicit.

**Comment by psychocoderHPC** [comment]
For me it is still not clear how this will affect the kernel start function in alpaka where alpaka is starting a parallel region `OMP2Thread`, or the parallel loop for our kernel emulation in `OMP2Blocks` or the workflow of DLR where the parallel region is created by the user. If clang-tidy is explicitly changing the code and enforcing that all data must be given into the parallel region/for I can imagine that we break one of the 3 workflows because we do not know which data must be available and shared and which private.

Currently, I see the problem that we break the runtime behavior if we set `default(none)`

**Comment by j-stephan** [comment]
In alpaka it would probably make sense to not enable this check. But since this is a general rule I think it might make sense to enable it in general and only turn it off where necessary.

**Comment by j-stephan** [comment]
@psychocoderHPC Ping!

**Comment by j-stephan** [comment]
Switching my OpenMP vote to no so we can finally close this...

**Pull request merged**
